name: Hello World
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"
             echo "I am Birendra Mahto"
      - name: Wish
        run: echo "Good morning"