
name: Github action ofr
on:
  push:
    branches:[main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      -name: Print node version
        run: node --version
 